### ISSUE TITLE
Place Order Error

### ISSUE THREAD

**Issue by afzalabbasi** [amir-the-h/okex#1]
@amir-the-h  i am unable to place the order. 
in response of Place order function i  found below error with status 50101
Msg:Broker id of APIKey does not match current environment.
check API key and secret the value of Key and secret is correct.
Important Point
I am using testmod of API.

**Comment by amir-the-h** [comment]
Hey @afzalabbasi

The issue you are facing now is according to your `API Key` and the destination server of OKX.
Check [here](https://www.okex.com/docs-v5/en/#overview-production-trading-services) for more info about the servers. And also make sure you choose the correct destination in your code when you are choosing it.

```go
dest := okex.NormalServer // The main API server
dest := okex. AwsServer // The main Amazon API server
dest := okex.DemoServer // The demo API server
```

**Comment by afzalabbasi** [comment]
@amir-the-h  thanks issue is fixed

**Comment by vantinic** [comment]
Hello @amir-the-h 

I have the same issue with the Java Api version
basically I try both: 

config.setEndpoint("https://www.okx.com/");
config.setEndpoint("https://aws.okx.com/");

And with a api key of demo trading, it works fine with both two rest endpoints

Unfortunately, when I try with-money real api keys (version 5) 
I give me the following error:

com.okex.open.api.exception.APIException: 50101 : APIKey does not match current environment.

(wich is the same issue as You solved before) 
This time is present at the same on Java Api version.
I went to the officia api documentation, it seems for real money there are no others choice betwwen that 2 endpoint for Rest.

Are there any suggestions ?


Thanks a lot in advance.

**Comment by Divyanshu0114** [comment]
> @amir-the-h i am unable to place the order. in response of Place order function i found below error with status 50101 Msg:Broker id of APIKey does not match current environment. check API key and secret the value of Key and secret is correct. Important Point I am using testmod of API.

hey, use this - 
flag = "0"  # live trading: 0, demo trading: 1
