### ISSUE TITLE
When the method is post, the data can definitely be passed in

### ISSUE THREAD

**Issue by LINJINTIANDE** [amir-the-h/okex#14]
If it is an array, this can only go back to the first data（https://github.com/amir-the-h/okex/blob/eb593335af79923723db716bf2d76b92ba4fdcf6/api/rest/client.go#L81）
If it is an array, okex.S2M(req) will also be empty when parsing

**Comment by amir-the-h** [comment]
Is it an assumption or a fact? Do you have any failures? If yes please provide. Hence I'll close the issue and you can re-open it when you had more information or a solution.

**Comment by LINJINTIANDE** [comment]
Run this method, the api provides an array and you provide a structure, resulting in an error（https://github.com/amir-the-h/okex/blob/eb593335af79923723db716bf2d76b92ba4fdcf6/api/rest/trade.go#L287）

**Comment by amir-the-h** [comment]
As I replied earlier I would really appreciate it if you can provide some examples of run time and errors. Otherwise, I can not follow up on this issue by providing theories.
