### ISSUE TITLE
[BUG] Wrong json field value in public market API

### ISSUE THREAD

**Issue by marperia** [amir-the-h/okex#16]
**Describe the bug**
I can't fetch tickers because of wrong JSON field declaration

**To Reproduce**
1. I took your readme example
2. I wrote some go code
```go
client.Rest.Market = rest.NewMarket(client.Rest)

getSwapTickers := market.GetTickers{
	InstType: okex.SwapInstrument,
}
swapTickers, err := client.Rest.Market.GetTickers(getSwapTickers)
if err != nil {
	log.Fatalln(err)
}
```
3. I saw the error
`json: invalid use of ,string struct tag, trying to unmarshal "SWAP" into okex.InstrumentType`

**Additional information**
Actually I have fixed it already, so it's just representative issue to make a PR

**Comment by amir-the-h** [comment]
@marperia Thanks for reporting this and sorry for the late response. I've been busy with my career recently. I left a review on your PR. If you can apply it we can merge your fix into the repo.
