### ISSUE TITLE
[BUG] goroutine leak in websocket api

### ISSUE THREAD

**Issue by bysomeone** [amir-the-h/okex#30]
**Describe the bug**
go channel reception has never been processed, resulting in continuous goroutine leaks

```go
case "mark-price":
			e := public.MarkPrice{}
			err := json.Unmarshal(data, &e)
			if err != nil {
				return false
			}
			go func() {
				if c.mpCh != nil {
					c.mpCh <- &e
				}
                       //goroutine stuck here
				c.StructuredEventChan <- e
			}()
			return true
```

**To Reproduce**
invoke websokcet subscribe api and receive websocket events with my own channels.

**Expected behavior**
goroutine exit properly

**Screenshots**

**Desktop (please complete the following information):**
 - Device: [e.g Macbook Pro]
 - OS: [e.g. MacOS]
 - Version [e.g. 14.1]

**Golang (please complete the following information):**
 - Version: [e.g. 17.1]

**Additional context**
version = v1.1.4-alpha

**Comment by dyamin** [comment]
I have fixed the issue in my fork: https://github.com/dyamin/go-okx
Additionally, I have submitted a PR to this repository
