### ISSUE TITLE
nil pointer dereference

### ISSUE THREAD

**Issue by renat1015** [amir-the-h/okex#5]
Hello @amir-the-h!
/github.com/amir-the-h/okex@v1.0.26-alpha/api/ws/client.go:238

   conn, res, err := websocket.DefaultDialer.Dial(string(c.url[p]), nil)
   defer res.Body.Close()

panic: runtime error: invalid memory address or nil pointer dereference

Can this problem be caused due to res nil?
Thanks!

**Comment by amir-the-h** [comment]
Hey @renat1015, you are probably right. I've merged your PR and released a new version. I'm currently not able to test it out. Try to checkout `v1.0.28-alpha` and give it a try.

Closed by #6

**Comment by renat1015** [comment]
call defer we fixed!
only the problem with the null pointer was not solved..
I added another merge request.
calling the dial function sometimes returns a res (*http.Response) nil when the error is not nil.
@amir-the-h thanks for the fast feedback!
