### ISSUE TITLE
WS orderBook method does not return data

### ISSUE THREAD

**Issue by renat1015** [amir-the-h/okex#8]
from v1.0.7-alpha version stopped receiving orderBook via web socket
up to v1.0.6-alpha version inclusive method client.Ws.Public.OrderBook(reqWS, obCh) returns data to the channel
so far I haven't looked deeper, maybe I'm doing something wrong

**Comment by amir-the-h** [comment]
@renat1015 Thanks for reporting it. I will work on it over the weekends and keep you update.

**Comment by amir-the-h** [comment]
Just an update. I had a rough week and was not able to work on it. But this won't be forgotten.

**Comment by renat1015** [comment]
Hi, @amir-the-h! Any news on this issue?
